'use client'
import type { Metadata } from "next";
import "./globals.css";
import {  Sidebar } from "@/components";



// export const metadata: Metadata = {
//   title: "Task Manager",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {




  return (
    <html lang="en">
      <body>
          <div className="flex h-full overflow-hidden">
            <Sidebar/>
            <div className=" flex-1 overflow-y-auto overscroll-contain">
              {children}
            </div>
          </div>
      </body>
    </html>
  );
}
