export const dummyChats = [
  {
    id: 1,
    chatName: "Rohit Sharma",
    message: "Bhai kal match dekhne aa raha hai?",
    timestamps: "1min ago",
    read: true,
  },
  {
    id: 2,
    chatName: "Sneha Patel",
    message: "Can you send me the assignment?",
    timestamps: "5min ago",
    read: false,
  },
  {
    id: 3,
    chatName: "Amit Verma",
    message: "Where are you bro?",
    timestamps: "8min ago",
    read: true,
  },
  {
    id: 4,
    chatName: "Priya Mehta",
    message: "I reached already, waiting outside.",
    timestamps: "10min ago",
    read: false,
  },
  {
    id: 5,
    chatName: "Vikas Deshmukh",
    message: "PDF mil gaya?",
    timestamps: "15min ago",
    read: true,
  },
  {
    id: 6,
    chatName: "Neha Reddy",
    message: "Are we still on for tonight?",
    timestamps: "18min ago",
    read: false,
  },
  {
    id: 7,
    chatName: "Ramesh Iyer",
    message: "Zoom link bhejna",
    timestamps: "22min ago",
    read: true,
  },
  {
    id: 8,
    chatName: "Megha Shah",
    message: "Haha that meme was too funny",
    timestamps: "25min ago",
    read: true,
  },
  {
    id: 9,
    chatName: "Karan Malhotra",
    message: "Lunch break kab le rahe?",
    timestamps: "30min ago",
    read: false,
  },
  {
    id: 10,
    chatName: "Anjali Sinha",
    message: "Call me when you’re free",
    timestamps: "35min ago",
    read: true,
  },
  {
    id: 11,
    chatName: "Siddharth Rao",
    message: "Check kar email",
    timestamps: "40min ago",
    read: false,
  },
  {
    id: 12,
    chatName: "Divya Nair",
    message: "Photos send kar na",
    timestamps: "45min ago",
    read: true,
  },
  {
    id: 13,
    chatName: "Manish Dubey",
    message: "Meeting abhi chalu hui kya?",
    timestamps: "50min ago",
    read: false,
  },
  {
    id: 14,
    chatName: "Ritika Jain",
    message: "Good morning! 😊",
    timestamps: "55min ago",
    read: true,
  },
  {
    id: 15,
    chatName: "Abhishek Joshi",
    message: "Kya tu aa raha gym?",
    timestamps: "1hr ago",
    read: false,
  },
  {
    id: 16,
    chatName: "Pooja Bhatt",
    message: "Send the notes please 🙏",
    timestamps: "1hr 5min ago",
    read: true,
  },
  {
    id: 17,
    chatName: "Raj Kapoor",
    message: "Work from home confirm hua?",
    timestamps: "1hr 10min ago",
    read: false,
  },
  {
    id: 18,
    chatName: "Shraddha Kaur",
    message: "Tum theek ho?",
    timestamps: "1hr 20min ago",
    read: true,
  },
  {
    id: 19,
    chatName: "Nikhil Saxena",
    message: "Got the parcel?",
    timestamps: "1hr 25min ago",
    read: false,
  },
  {
    id: 20,
    chatName: "Tanvi Agarwal",
    message: "Lunch ho gaya?",
    timestamps: "1hr 30min ago",
    read: true,
  },
  {
    id: 21,
    chatName: "Varun Yadav",
    message: "Ping me when done",
    timestamps: "2hr ago",
    read: false,
  },
  {
    id: 22,
    chatName: "Simran Bhatia",
    message: "Kal ka plan kya hai?",
    timestamps: "2hr 5min ago",
    read: true,
  },
  {
    id: 23,
    chatName: "Harshit Tiwari",
    message: "Yo what’s the update?",
    timestamps: "2hr 10min ago",
    read: false,
  },
  {
    id: 24,
    chatName: "Naina Kapoor",
    message: "Class kab hai?",
    timestamps: "2hr 15min ago",
    read: true,
  },
  {
    id: 25,
    chatName: "Deepak Chauhan",
    message: "Battery low, ttyl",
    timestamps: "2hr 20min ago",
    read: false,
  },
  {
    id: 26,
    chatName: "Kritika Das",
    message: "Please upload the doc",
    timestamps: "2hr 30min ago",
    read: true,
  },
  {
    id: 27,
    chatName: "Mayank Pandey",
    message: "Bhai kal ka leave laga diya?",
    timestamps: "2hr 45min ago",
    read: false,
  },
  {
    id: 28,
    chatName: "Ishita Sen",
    message: "Tu bohot funny hai 😂",
    timestamps: "3hr ago",
    read: true,
  },
  {
    id: 29,
    chatName: "Yash Bhargava",
    message: "Ping me for Zoom later",
    timestamps: "3hr 15min ago",
    read: false,
  },
  {
    id: 30,
    chatName: "Payal Jha",
    message: "Where’s the party yaar?",
    timestamps: "3hr 30min ago",
    read: true,
  },
];

export const mentorData = [
  {
    id: 1,
    isDetails: true,
    name: "Aarav Gupta",
    role: "React Developer",
    tasks: 42,
    rating: 4.5,
    reviews: 325,
    selfIntro:
      "Hey My Self Aarav Gupta and I am a passionate React Developer specializing in component-driven UI and seamless UX magic.",
  },
  {
    id: 2,
    isDetails: false,
    name: "Sneha Sharma",
    role: "Fullstack Developer",
    tasks: 38,
    rating: 4.7,
    reviews: 410,
    selfIntro:
      "Hey My Self Sneha Sharma and I am a Fullstack Developer who breathes React, Node, and coffee. Code is my second language!",
  },
  {
    id: 3,
    isDetails: true,
    name: "Raj Mehta",
    role: "Backend Engineer",
    tasks: 50,
    rating: 4.8,
    reviews: 289,
    selfIntro:
      "Hey My Self Raj Mehta and I am a Backend Engineer who builds scalable APIs and makes sure your server never cries.",
  },
  {
    id: 4,
    isDetails: false,
    name: "Neha Iyer",
    role: "UX/UI Designer",
    tasks: 30,
    rating: 4.3,
    reviews: 150,
    selfIntro:
      "Hey My Self Neha Iyer and I create pixel-perfect designs that speak to users like poetry in motion.",
  },
  {
    id: 5,
    isDetails: true,
    name: "Amitabh Reddy",
    role: "Node.js Specialist",
    tasks: 45,
    rating: 4.6,
    reviews: 389,
    selfIntro:
      "Hey My Self Amitabh Reddy and I craft backend systems in Node.js that scale smoother than ghee on a hot paratha.",
  },
  {
    id: 6,
    isDetails: false,
    name: "Riya Kapoor",
    role: "Frontend Wizard",
    tasks: 36,
    rating: 4.9,
    reviews: 422,
    selfIntro:
      "Hey My Self Riya Kapoor and I conjure delightful frontends with React, TypeScript, and a sprinkle of Tailwind magic.",
  },
  {
    id: 7,
    isDetails: true,
    name: "Kunal Saxena",
    role: "MERN Stack Dev",
    tasks: 48,
    rating: 4.4,
    reviews: 333,
    selfIntro:
      "Hey My Self Kunal Saxena and I build fullstack MERN applications that users love and databases respect.",
  },
  {
    id: 8,
    isDetails: true,
    name: "Ishita Sen",
    role: "Mobile App Dev",
    tasks: 25,
    rating: 4.1,
    reviews: 198,
    selfIntro:
      "Hey My Self Ishita Sen and I craft seamless mobile experiences using Flutter and React Native.",
  },
  {
    id: 9,
    isDetails: false,
    name: "Raghav Joshi",
    role: "Cloud Architect",
    tasks: 55,
    rating: 4.8,
    reviews: 510,
    selfIntro:
      "Hey My Self Raghav Joshi and I architect reliable, scalable cloud systems with AWS and a dash of Kubernetes power.",
  },
  {
    id: 10,
    isDetails: true,
    name: "Priya Nair",
    role: "Data Scientist",
    tasks: 29,
    rating: 4.2,
    reviews: 140,
    selfIntro:
      "Hey My Self Priya Nair and I turn data into stories, using Python, Pandas, and machine learning models that talk sense.",
  },
  {
    id: 11,
    isDetails: true,
    name: "Yash Malhotra",
    role: "AI/ML Engineer",
    tasks: 33,
    rating: 4.7,
    reviews: 320,
    selfIntro:
      "Hey My Self Yash Malhotra and I train intelligent models that learn like humans and compute like machines.",
  },
  {
    id: 12,
    isDetails: false,
    name: "Tanya Jain",
    role: "Product Designer",
    tasks: 21,
    rating: 4.0,
    reviews: 104,
    selfIntro:
      "Hey My Self Tanya Jain and I design digital products that users fall in love with, one interaction at a time.",
  },
  {
    id: 13,
    isDetails: true,
    name: "Dev Sharma",
    role: "Django Developer",
    tasks: 39,
    rating: 4.5,
    reviews: 278,
    selfIntro:
      "Hey My Self Dev Sharma and I am a Django Developer who builds secure, scalable, and sensible web backends.",
  },
  {
    id: 14,
    isDetails: false,
    name: "Anjali Bhatt",
    role: "Business Analyst",
    tasks: 26,
    rating: 4.4,
    reviews: 143,
    selfIntro:
      "Hey My Self Anjali Bhatt and I analyze business needs and convert them into software that gets results.",
  },
  {
    id: 15,
    isDetails: true,
    name: "Mohit Rao",
    role: "Flutter Dev",
    tasks: 34,
    rating: 4.6,
    reviews: 199,
    selfIntro:
      "Hey My Self Mohit Rao and I build cross-platform mobile apps with Flutter that run like butter.",
  },
  {
    id: 16,
    isDetails: false,
    name: "Kritika Das",
    role: "WordPress Guru",
    tasks: 18,
    rating: 4.2,
    reviews: 80,
    selfIntro:
      "Hey My Self Kritika Das and I craft high-performing WordPress websites that look sharp and load fast.",
  },
  {
    id: 17,
    isDetails: true,
    name: "Vikram Bansal",
    role: "SDE 2 @ Amazon",
    tasks: 49,
    rating: 4.9,
    reviews: 672,
    selfIntro:
      "Hey My Self Vikram Bansal and I solve big problems with small elegant solutions. Currently at Amazon.",
  },
  {
    id: 18,
    isDetails: false,
    name: "Simran Kaur",
    role: "Fullstack Intern",
    tasks: 22,
    rating: 4.1,
    reviews: 109,
    selfIntro:
      "Hey My Self Simran Kaur and I’m a Fullstack Intern eager to learn, build, and ship meaningful code.",
  },
  {
    id: 19,
    isDetails: true,
    name: "Harshit Tiwari",
    role: "System Designer",
    tasks: 41,
    rating: 4.3,
    reviews: 287,
    selfIntro:
      "Hey My Self Harshit Tiwari and I design resilient systems that can handle traffic better than Mumbai roads.",
  },
  {
    id: 20,
    isDetails: false,
    name: "Megha Patil",
    role: "SQL Expert",
    tasks: 23,
    rating: 4.0,
    reviews: 134,
    selfIntro:
      "Hey My Self Megha Patil and I speak fluent SQL, tune queries, and keep your database snappy.",
  },
  {
    id: 21,
    isDetails: true,
    name: "Tanmay Desai",
    role: "Ethical Hacker",
    tasks: 37,
    rating: 4.8,
    reviews: 312,
    selfIntro:
      "Hey My Self Tanmay Desai and I protect systems from the shadows — your friendly ethical hacker next door.",
  },
  {
    id: 22,
    isDetails: false,
    name: "Swati Chavan",
    role: "AWS Consultant",
    tasks: 46,
    rating: 4.6,
    reviews: 421,
    selfIntro:
      "Hey My Self Swati Chavan and I help businesses scale with cloud-native architectures on AWS.",
  },
  {
    id: 23,
    isDetails: true,
    name: "Nitin Agrawal",
    role: "Python Ninja",
    tasks: 32,
    rating: 4.7,
    reviews: 289,
    selfIntro:
      "Hey My Self Nitin Agrawal and I code clean Python, automate boring stuff, and occasionally write memes.",
  },
  {
    id: 24,
    isDetails: true,
    name: "Jhanvi Vyas",
    role: "UI Dev Intern",
    tasks: 19,
    rating: 4.2,
    reviews: 94,
    selfIntro:
      "Hey My Self Jhanvi Vyas and I build crisp user interfaces and am hungry to learn more every day.",
  },
  {
    id: 25,
    isDetails: false,
    name: "Saurabh Dey",
    role: "Kubernetes Admin",
    tasks: 53,
    rating: 4.9,
    reviews: 530,
    selfIntro:
      "Hey My Self Saurabh Dey and I orchestrate containers like a maestro on Kubernetes.",
  },
  {
    id: 26,
    isDetails: true,
    name: "Diya Mahajan",
    role: "Golang Dev",
    tasks: 28,
    rating: 4.4,
    reviews: 214,
    selfIntro:
      "Hey My Self Diya Mahajan and I write fast, reliable Go code for backend systems that never flinch.",
  },
  {
    id: 27,
    isDetails: false,
    name: "Pranav Kulkarni",
    role: "PostgreSQL Expert",
    tasks: 31,
    rating: 4.3,
    reviews: 189,
    selfIntro:
      "Hey My Self Pranav Kulkarni and I tame relational dragons with PostgreSQL and query optimization.",
  },
  {
    id: 28,
    isDetails: true,
    name: "Shreya Ghosh",
    role: "Tech Content Creator",
    tasks: 40,
    rating: 4.5,
    reviews: 298,
    selfIntro:
      "Hey My Self Shreya Ghosh and I simplify complex tech concepts through words and visuals.",
  },
  {
    id: 29,
    isDetails: false,
    name: "Udayan Chawla",
    role: "DevOps Lead",
    tasks: 51,
    rating: 4.8,
    reviews: 465,
    selfIntro:
      "Hey My Self Udayan Chawla and I automate infrastructure and deploy faster than you say 'CI/CD'.",
  },
  {
    id: 30,
    isDetails: true,
    name: "Aishwarya Dixit",
    role: "Frontend Freelancer",
    tasks: 27,
    rating: 4.1,
    reviews: 137,
    selfIntro:
      "Hey My Self Aishwarya Dixit and I freelance as a frontend dev, turning figma files into beautiful websites.",
  },
];

export const upcomingTask = [
  {
    id: 1,
    taskName: "Design Landing Page",
    task: "UI UX Design",
    progress: 75,
    daysLeft: 3,
    src: "/image2.png",
  },
  {
    id: 2,
    taskName: "Build REST API",
    task: "Backend Development",
    progress: 60,
    daysLeft: 5,
    src: "/image4.png",
  },
  {
    id: 3,
    taskName: "Setup Firebase Auth",
    task: "Authentication",
    progress: 90,
    daysLeft: 1,
    src: "/image1.png",
  },
  {
    id: 4,
    taskName: "Fix UI Bugs",
    task: "Debugging",
    progress: 40,
    daysLeft: 4,
    src: "/image5.png",
  },
  {
    id: 5,
    taskName: "Deploy to Vercel",
    task: "Deployment",
    progress: 20,
    daysLeft: 2,
    src: "/image.png",
  },
  {
    id: 6,
    taskName: "Design Onboarding Screens",
    task: "UI UX Design",
    progress: 85,
    daysLeft: 6,
    src: "/image3.png",
  },
  {
    id: 7,
    taskName: "Implement Search Feature",
    task: "Frontend Development",
    progress: 50,
    daysLeft: 3,
    src: "/image2.png",
  },
  {
    id: 8,
    taskName: "Create Admin Panel",
    task: "Dashboard",
    progress: 65,
    daysLeft: 7,
    src: "/image1.png",
  },
  {
    id: 9,
    taskName: "Write Unit Tests",
    task: "Testing",
    progress: 30,
    daysLeft: 4,
    src: "/image.png",
  },
  {
    id: 10,
    taskName: "Integrate Payment Gateway",
    task: "E-Commerce",
    progress: 95,
    daysLeft: 1,
    src: "/image5.png",
  },
  {
    id: 11,
    taskName: "Refactor Codebase",
    task: "Code Quality",
    progress: 70,
    daysLeft: 5,
    src: "/image4.png",
  },
  {
    id: 12,
    taskName: "Configure ESLint & Prettier",
    task: "Dev Tools",
    progress: 90,
    daysLeft: 2,
    src: "/image3.png",
  },
  {
    id: 13,
    taskName: "Research Competitors",
    task: "Market Analysis",
    progress: 45,
    daysLeft: 6,
    src: "/image2.png",
  },
  {
    id: 14,
    taskName: "Setup MongoDB Cluster",
    task: "Database",
    progress: 55,
    daysLeft: 3,
    src: "/image.png",
  },
  {
    id: 15,
    taskName: "Animate Components",
    task: "Frontend Dev",
    progress: 35,
    daysLeft: 4,
    src: "/image1.png",
  },
  {
    id: 16,
    taskName: "Optimize Performance",
    task: "Performance",
    progress: 50,
    daysLeft: 2,
    src: "/image4.png",
  },
  {
    id: 17,
    taskName: "Setup GitHub Actions",
    task: "CI/CD",
    progress: 65,
    daysLeft: 5,
    src: "/image3.png",
  },
  {
    id: 18,
    taskName: "Design Logo",
    task: "Branding",
    progress: 20,
    daysLeft: 3,
    src: "/image5.png",
  },
  {
    id: 19,
    taskName: "Connect to API",
    task: "Integration",
    progress: 80,
    daysLeft: 2,
    src: "/image.png",
  },
  {
    id: 20,
    taskName: "Fix Mobile Responsiveness",
    task: "Frontend Fixes",
    progress: 75,
    daysLeft: 4,
    src: "/image1.png",
  },
  {
    id: 21,
    taskName: "Setup Redux Toolkit",
    task: "State Management",
    progress: 55,
    daysLeft: 3,
    src: "/image2.png",
  },
  {
    id: 22,
    taskName: "Integrate Chat Feature",
    task: "Messaging",
    progress: 45,
    daysLeft: 5,
    src: "/image3.png",
  },
  {
    id: 23,
    taskName: "Write Documentation",
    task: "Dev Docs",
    progress: 90,
    daysLeft: 1,
    src: "/image4.png",
  },
  {
    id: 24,
    taskName: "Conduct User Interviews",
    task: "User Research",
    progress: 25,
    daysLeft: 6,
    src: "/image5.png",
  },
  {
    id: 25,
    taskName: "Add Dark Mode",
    task: "UI Enhancement",
    progress: 60,
    daysLeft: 2,
    src: "/image.png",
  },
  {
    id: 26,
    taskName: "Setup Webhooks",
    task: "Backend",
    progress: 50,
    daysLeft: 3,
    src: "/image2.png",
  },
  {
    id: 27,
    taskName: "Create Portfolio Section",
    task: "Frontend",
    progress: 70,
    daysLeft: 4,
    src: "/image1.png",
  },
  {
    id: 28,
    taskName: "Implement SEO",
    task: "Optimization",
    progress: 40,
    daysLeft: 5,
    src: "/image3.png",
  },
  {
    id: 29,
    taskName: "Update Privacy Policy",
    task: "Legal",
    progress: 30,
    daysLeft: 2,
    src: "/image4.png",
  },
  {
    id: 30,
    taskName: "Test Cross-Browser Support",
    task: "QA",
    progress: 85,
    daysLeft: 3,
    src: "/image5.png",
  },
];


